sonar.projectKey=mvspec
sonar.projectName=mvspec
sonar.projectVersion=1.0.0

sonar.sources=internal/config,internal/scanner,internal/generator,internal/embed,internal/parser/go,internal/parser/js,internal/util,cmd/mvspec

sonar.sourceEncoding=UTF-8
sonar.go.coverage.reportPaths=coverage

sonar.exclusions=**/vendor/**,**/*_test.go,sonar-project.properties,coverage,.gitignore